### PR TITLE
Remove the cache folder at the end of the installation

### PR DESCRIPTION
**Pull request by asimlqt**

### CODE REVIEW

**Comment by seeruk** [comment]
The whole point in the cache folder is to cache the download. It must still exist so that composer install / update doesn't doesn't take a long time because it's downloading and extracting Pimcore again. This change would remove that, and make the build process on Jenkins, and install / update on local machines far slower.

If your IDE Is indexing it, you should ignore it in your IDE. In JetBrains IDEs you can right click on the folder, and mark the folder as excluded. 

You should be able to do the same in NetBeans, it might be different to this in a newer version: https://blogs.oracle.com/netbeansphp/entry/ignored_folders_sure or maybe http://stackoverflow.com/questions/2558213/how-do-you-make-netbeans-ignore-files-when-searching-for-files

**Comment by asimlqt** [comment]
I have to add an ignore on my work pc, my laptop and my home desktop and that's just one project. I'll have to do it for every project that uses this lib. Also anyone who uses this library will need to do it as well.

It doesn't delete the downloaded zip file, just the cache directory. But yes it will have to unpack it and copy the files across.

Realistically, the files should only be copied if they need copying. I'll update the PR to check if Pimcore has already been installed. If it has we can skip this process entirely.

**Comment by seeruk** [comment]
That is a one time thing though, the first time you use the project. I'm sure you do other things in your IDE per-project like set up your debugger for example.

We can maybe come to a compromise, but we need this to work on Windows still too. I was thinking we could maybe put it in /tmp on *nix systems, but realistically anywhere other than the current directory is going to cause a compatibility issue with some other OS unfortunately.

Also, I'm pretty sure the extraction can take longer than the download, so if we're going to keep any part of this then it should be the already extracted files!

Finally, making a check to see if Pimcore is already installed would only be able to benefit local environments, to any other environment it would be a detriment. The reason it does copy over every time is to ensure you're not messing with Pimcore code.

**Comment by seeruk** [comment]
So, as we discussed on the train, maybe we can extract the Pimcore archive straight to where it will be copied to. This preserves everything we want I believe, and might even decrease install time...

**Comment by asimlqt** [comment]
I still think the better option is to check if Pimcore is already installed and what version it is. If it's the same version then there's no need to do any extracting or copying at all. It can't be any faster than that.

On that basis it will still work on every OS, it will be fast and Pimcore is never committed to any repository that I've seen. It's always git ignored so there's no need to worry about anyone modifying the Pimcore.

**Comment by seeruk** [comment]
I'm pretty keen to keep the overwriting to be honest. I think if we just extract straight to where it is, we don't have the indexing problem, we have a smaller build artifact, it's faster, and we aren't forced to make builds in automated build systems clean out all of the Pimcore files beforehand to ensure they're the stock files (which we would need to do, there can be no risk at all that we are deploying some modified Pimcore files without knowing it, otherwise we cannot use this library).

Compared to the approach you want to make, the trade of is between greater increase in installation speed, vs. still an increase in installation speed but also with the safety that you know as part of your automated build you are 100% definitely getting the right Pimcore version.

**Pull request closed without merging**
